<?php
declare(strict_types=1);
namespace App\Entity;
use App\Repository\CourseRepository;use Doctrine\Common\Collections\{ArrayCollection,Collection};use Doctrine\DBAL\Types\Types;use Doctrine\ORM\Mapping as ORM;
#[ORM\Entity(repositoryClass:CourseRepository::class)] #[ORM\Table(name:'courses')]
class Course
{
 #[ORM\Id,ORM\GeneratedValue,ORM\Column]private ?int $id=null;#[ORM\Column(length:160)]private string $name='';#[ORM\Column(length:160,nullable:true)]private ?string $ageGroup=null;#[ORM\ManyToOne,ORM\JoinColumn(nullable:false)]private Department $department;/** @var Collection<int,User> */#[ORM\ManyToMany(targetEntity:User::class),ORM\JoinTable(name:'course_trainers')]private Collection $trainers;#[ORM\Column]private bool $active=true;#[ORM\Column(type:Types::DATE_IMMUTABLE,nullable:true)]private ?\DateTimeImmutable $validFrom=null;#[ORM\Column(type:Types::DATE_IMMUTABLE,nullable:true)]private ?\DateTimeImmutable $validUntil=null;
 public function __construct(){$this->trainers=new ArrayCollection();}public function getId():?int{return $this->id;}public function getName():string{return $this->name;}public function setName(string $v):self{$this->name=trim($v);return $this;}public function getAgeGroup():?string{return $this->ageGroup;}public function setAgeGroup(?string $v):self{$this->ageGroup=$v;return $this;}public function getDepartment():Department{return $this->department;}public function setDepartment(Department $v):self{$this->department=$v;return $this;}/** @return Collection<int,User> */public function getTrainers():Collection{return $this->trainers;}public function clearTrainers():self{$this->trainers->clear();return $this;}public function addTrainer(User $v):self{if(!$this->trainers->contains($v))$this->trainers->add($v);return $this;}public function isActive():bool{return $this->active;}public function setActive(bool $v):self{$this->active=$v;return $this;}public function getValidFrom():?\DateTimeImmutable{return $this->validFrom;}public function setValidFrom(?\DateTimeImmutable $v):self{$this->validFrom=$v;return $this;}public function getValidUntil():?\DateTimeImmutable{return $this->validUntil;}public function setValidUntil(?\DateTimeImmutable $v):self{$this->validUntil=$v;return $this;}public function isValidAt(?\DateTimeImmutable $at=null):bool{$at??=new \DateTimeImmutable('today',new \DateTimeZone('Europe/Berlin'));return $this->active&&(!$this->validFrom||$this->validFrom<=$at)&&(!$this->validUntil||$this->validUntil>=$at);}
}
