<?php
declare(strict_types=1); namespace App\Controller;
use App\Entity\UserInvitation; use Doctrine\ORM\EntityManagerInterface; use Symfony\Bundle\FrameworkBundle\Controller\AbstractController; use Symfony\Component\HttpFoundation\Request; use Symfony\Component\HttpFoundation\Response; use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface; use Symfony\Component\Routing\Attribute\Route; use Symfony\Component\Security\Http\Authentication\AuthenticationUtils;
final class AuthenticationController extends AbstractController {
 #[Route('/editor/login',name:'app_login',methods:['GET','POST'])] public function login(AuthenticationUtils $a):Response{return $this->render('admin/login.html.twig',['error'=>$a->getLastAuthenticationError(),'configured'=>true]);}
 #[Route('/editor/logout',name:'app_logout',methods:['GET'])] public function logout():never{throw new \LogicException('Handled by firewall.');}
 #[Route('/invitation/{token}',name:'invitation_accept',methods:['GET','POST'])] public function invitation(string $token,Request $r,EntityManagerInterface $em,UserPasswordHasherInterface $hasher):Response{$invite=$em->getRepository(UserInvitation::class)->findOneBy(['tokenHash'=>hash('sha256',$token)]);if(!$invite instanceof UserInvitation||!$invite->isUsable())throw $this->createNotFoundException('Einladung ungültig oder abgelaufen.');$error=null;if($r->isMethod('POST')){$password=(string)$r->request->get('password');if(!$this->isCsrfTokenValid('invitation-'.$token,(string)$r->request->get('_token')))throw $this->createAccessDeniedException();if(strlen($password)<12||$password!==(string)$r->request->get('password_repeat'))$error='Passwörter müssen übereinstimmen und mindestens 12 Zeichen lang sein.';else{$invite->getUser()->setPassword($hasher->hashPassword($invite->getUser(),$password));$invite->accept();$em->flush();$this->addFlash('success','Passwort gesetzt. Du kannst dich jetzt anmelden.');return $this->redirectToRoute('app_login');}}return $this->render('admin/invitation.html.twig',['invitation'=>$invite,'token'=>$token,'error'=>$error]);}
 #[Route('/password/change',name:'password_change',methods:['GET','POST'])] public function password(Request $r,UserPasswordHasherInterface $hasher,EntityManagerInterface $em):Response{$user=$this->getUser();$error=null;if($r->isMethod('POST')&&$user instanceof \App\Entity\User){if(!$this->isCsrfTokenValid('password-change',(string)$r->request->get('_token')))throw $this->createAccessDeniedException();$old=(string)$r->request->get('current_password');$new=(string)$r->request->get('password');if(!$hasher->isPasswordValid($user,$old))$error='Das aktuelle Passwort ist falsch.';elseif(strlen($new)<12||$new!==(string)$r->request->get('password_repeat'))$error='Das neue Passwort muss übereinstimmen und mindestens 12 Zeichen lang sein.';else{$user->setPassword($hasher->hashPassword($user,$new));$em->flush();$this->addFlash('success','Passwort geändert.');return $this->redirectToRoute('editor_dashboard');}}return $this->render('admin/password.html.twig',['error'=>$error]);}
}
